# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\Display_objects.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_display_items(object):
    def setupUi(self, Dialog_display_items):
        Dialog_display_items.setObjectName("Dialog_display_items")
        Dialog_display_items.resize(380, 130)
        Dialog_display_items.setMinimumSize(QtCore.QSize(380, 130))
        Dialog_display_items.setMaximumSize(QtCore.QSize(380, 130))
        self.labelTitle_display_object = QtWidgets.QLabel(Dialog_display_items)
        self.labelTitle_display_object.setGeometry(QtCore.QRect(0, 0, 380, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.labelTitle_display_object.setFont(font)
        self.labelTitle_display_object.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle_display_object.setObjectName("labelTitle_display_object")
        self.progressBar = QtWidgets.QProgressBar(Dialog_display_items)
        self.progressBar.setGeometry(QtCore.QRect(10, 60, 361, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_return = QtWidgets.QPushButton(Dialog_display_items)
        self.pushButton_return.setGeometry(QtCore.QRect(140, 90, 101, 28))
        self.pushButton_return.setObjectName("pushButton_return")
        self.label_progression = QtWidgets.QLabel(Dialog_display_items)
        self.label_progression.setGeometry(QtCore.QRect(10, 40, 331, 20))
        self.label_progression.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_progression.setObjectName("label_progression")

        self.retranslateUi(Dialog_display_items)
        QtCore.QMetaObject.connectSlotsByName(Dialog_display_items)

    def retranslateUi(self, Dialog_display_items):
        _translate = QtCore.QCoreApplication.translate
        Dialog_display_items.setWindowTitle(_translate("Dialog_display_items", "Dialog"))
        self.labelTitle_display_object.setText(_translate("Dialog_display_items", "<html><head/><body><p><span style=\" font-size:18pt; color:#3366cc;\">Affichage des XXX</span></p></body></html>"))
        self.pushButton_return.setText(_translate("Dialog_display_items", "Annuler"))
        self.label_progression.setText(_translate("Dialog_display_items", "xxx/yyy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_display_items = QtWidgets.QDialog()
    ui = Ui_Dialog_display_items()
    ui.setupUi(Dialog_display_items)
    Dialog_display_items.show()
    sys.exit(app.exec_())
