# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\Import_datastruct.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 160)
        Dialog.setMinimumSize(QtCore.QSize(300, 160))
        Dialog.setMaximumSize(QtCore.QSize(300, 160))
        self.labelTitle_dataImport = QtWidgets.QLabel(Dialog)
        self.labelTitle_dataImport.setGeometry(QtCore.QRect(0, 0, 301, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.labelTitle_dataImport.setFont(font)
        self.labelTitle_dataImport.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle_dataImport.setObjectName("labelTitle_dataImport")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 59, 261, 47))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_userEntries = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_userEntries.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_userEntries.setObjectName("gridLayout_userEntries")
        self.label_selectFile = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_selectFile.setObjectName("label_selectFile")
        self.gridLayout_userEntries.addWidget(self.label_selectFile, 0, 0, 1, 1)
        self.toolButton_selectFile = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_selectFile.setObjectName("toolButton_selectFile")
        self.gridLayout_userEntries.addWidget(self.toolButton_selectFile, 0, 1, 1, 1)
        self.label_selection = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_selection.setObjectName("label_selection")
        self.gridLayout_userEntries.addWidget(self.label_selection, 1, 0, 1, 1)
        self.label_FileName = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_FileName.setObjectName("label_FileName")
        self.gridLayout_userEntries.addWidget(self.label_FileName, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 110, 261, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_validateReturn = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_validateReturn.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_validateReturn.setObjectName("horizontalLayout_validateReturn")
        self.pushButton_Validation = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Validation.setObjectName("pushButton_Validation")
        self.horizontalLayout_validateReturn.addWidget(self.pushButton_Validation)
        self.pushButton_return = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_return.setObjectName("pushButton_return")
        self.horizontalLayout_validateReturn.addWidget(self.pushButton_return)

        self.retranslateUi(Dialog)
        self.toolButton_selectFile.clicked.connect(self.label_selection.show)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.toolButton_selectFile, self.pushButton_Validation)
        Dialog.setTabOrder(self.pushButton_Validation, self.pushButton_return)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelTitle_dataImport.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; color:#3366cc;\">Import de données</span></p></body></html>"))
        self.label_selectFile.setText(_translate("Dialog", "Selectionner le fichier :"))
        self.toolButton_selectFile.setText(_translate("Dialog", "..."))
        self.label_selection.setText(_translate("Dialog", "Selection :"))
        self.label_FileName.setText(_translate("Dialog", "FileName"))
        self.pushButton_Validation.setText(_translate("Dialog", "Valider"))
        self.pushButton_return.setText(_translate("Dialog", "Retour"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
