# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '0_MenuPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogMenuPrincipal(object):
    def setupUi(self, dialogMenuPrincipal, listExport):
        dialogMenuPrincipal.setObjectName("dialogMenuPrincipal")
        dialogMenuPrincipal.resize(500, 700)
        dialogMenuPrincipal.setMinimumSize(QtCore.QSize(500, 700))
        dialogMenuPrincipal.setMaximumSize(QtCore.QSize(500, 700))
        self.labelTitleMenu = QtWidgets.QLabel(dialogMenuPrincipal)
        self.labelTitleMenu.setGeometry(QtCore.QRect(0, 50, 500, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.labelTitleMenu.setFont(font)
        self.labelTitleMenu.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitleMenu.setObjectName("labelTitleMenu")
        self.verticalLayoutWidget = QtWidgets.QWidget(dialogMenuPrincipal)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 140, 281, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.LayoutMenu = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.LayoutMenu.setContentsMargins(0, 0, 0, 0)
        self.LayoutMenu.setObjectName("LayoutMenu")
        self.btnMenulayersCreation = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnMenulayersCreation.setObjectName("btnMenulayersCreation")
        self.LayoutMenu.addWidget(self.btnMenulayersCreation)
        self.btnMenuPerimetersTrajectories = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnMenuPerimetersTrajectories.setObjectName("btnMenuPerimetersTrajectories")
        self.LayoutMenu.addWidget(self.btnMenuPerimetersTrajectories)
        self.btnMenuInfillTrajectories = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnMenuInfillTrajectories.setObjectName("btnMenuInfillTrajectories")
        self.LayoutMenu.addWidget(self.btnMenuInfillTrajectories)
        self.btnMenuMachineParameters = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnMenuMachineParameters.setObjectName("btnMenuMachineParameters")
        self.LayoutMenu.addWidget(self.btnMenuMachineParameters)
        self.btnMenuDiscretizationTrajectories = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnMenuDiscretizationTrajectories.setObjectName("btnMenuDiscretizationTrajectories")
        self.LayoutMenu.addWidget(self.btnMenuDiscretizationTrajectories)
        self.btnMenuDiscretisationAnnulation = QtWidgets.QPushButton(self.verticalLayoutWidget)
        #self.btnMenuDiscretisationAnnulation.setEnabled(False)
        #self.btnMenuDiscretisationAnnulation.setDisabled(True)
        self.btnMenuDiscretisationAnnulation.setObjectName("btnMenuDiscretisationAnnulation")
        self.LayoutMenu.addWidget(self.btnMenuDiscretisationAnnulation)
        self.btnMenuExportCsv = QtWidgets.QPushButton(self.verticalLayoutWidget)
        #self.btnMenuExportCsv.setEnabled(False)
        #self.btnMenuExportCsv.setDisabled(True)
        self.btnMenuExportCsv.setObjectName("btnMenuExportCsv")
        self.LayoutMenu.addWidget(self.btnMenuExportCsv)
        if listExport:
            self.btnMenuDiscretisationAnnulation.setDisabled(False)
            self.btnMenuExportCsv.setDisabled(False)
        else:
            self.btnMenuDiscretisationAnnulation.setDisabled(True)
            self.btnMenuExportCsv.setDisabled(True)

        self.retranslateUi(dialogMenuPrincipal)
        self.btnMenuDiscretizationTrajectories.clicked.connect(self.btnMenuExportCsv.show)
        self.btnMenuDiscretizationTrajectories.clicked.connect(self.btnMenuDiscretisationAnnulation.show)
        QtCore.QMetaObject.connectSlotsByName(dialogMenuPrincipal)

    def retranslateUi(self, dialogMenuPrincipal):
        _translate = QtCore.QCoreApplication.translate
        dialogMenuPrincipal.setWindowTitle(_translate("dialogMenuPrincipal", "Menu Principal"))
        self.labelTitleMenu.setText(_translate("dialogMenuPrincipal", "<span style=\" font-size:24pt; color:#3366CC;\">Slicer 6 axes </span>"))
        self.btnMenulayersCreation.setText(_translate("dialogMenuPrincipal", "Création de couches de dépose"))
        self.btnMenuPerimetersTrajectories.setText(_translate("dialogMenuPrincipal", "Trajectoires de contours"))
        self.btnMenuInfillTrajectories.setText(_translate("dialogMenuPrincipal", "Tajectoires de remplissage"))
        self.btnMenuMachineParameters.setText(_translate("dialogMenuPrincipal", "Paramètres machine"))
        self.btnMenuDiscretizationTrajectories.setText(_translate("dialogMenuPrincipal", "Discretisation de trajectoires"))
        self.btnMenuDiscretisationAnnulation.setText(_translate("dialogMenuPrincipal", "Annuler une discrétisation"))
        self.btnMenuExportCsv.setText(_translate("dialogMenuPrincipal", "Export des coordonnées"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialogMenuPrincipal = QtWidgets.QDialog()
    ui = Ui_dialogMenuPrincipal()
    ui.setupUi(dialogMenuPrincipal)
    dialogMenuPrincipal.show()
    sys.exit(app.exec_())
