# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\Object_found_in_datastruct.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(440, 120)
        Dialog.setMinimumSize(QtCore.QSize(340, 120))
        Dialog.setMaximumSize(QtCore.QSize(440, 120))
        self.labelTitle_alreadyExistingObject = QtWidgets.QLabel(Dialog)
        self.labelTitle_alreadyExistingObject.setGeometry(QtCore.QRect(0, 0, 441, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.labelTitle_alreadyExistingObject.setFont(font)
        self.labelTitle_alreadyExistingObject.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle_alreadyExistingObject.setObjectName("labelTitle_alreadyExistingObject")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 401, 55))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.horizontalLayout_validateReplaceIgnore = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.horizontalLayout_validateReplaceIgnore.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_validateReplaceIgnore.setObjectName("horizontalLayout_validateReplaceIgnore")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_validateReplaceIgnore.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_continue = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_continue.setObjectName("pushButton_continue")
        self.horizontalLayout.addWidget(self.pushButton_continue)
        self.pushButton_replace = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_replace.setObjectName("pushButton_replace")
        self.horizontalLayout.addWidget(self.pushButton_replace)
        self.pushButton_ignore = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_ignore.setObjectName("pushButton_ignore")
        self.horizontalLayout.addWidget(self.pushButton_ignore)
        self.pushButton_ignoreAll = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_ignoreAll.setObjectName("pushButton_ignoreAll")
        self.horizontalLayout.addWidget(self.pushButton_ignoreAll)
        self.horizontalLayout_validateReplaceIgnore.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelTitle_alreadyExistingObject.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; color:#3366cc;\">Objet déja éxistant</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "Que faire ?"))
        self.pushButton_continue.setText(_translate("Dialog", "Continuer"))
        self.pushButton_replace.setText(_translate("Dialog", "Remplacer"))
        self.pushButton_ignore.setText(_translate("Dialog", "Ignorer"))
        self.pushButton_ignoreAll.setText(_translate("Dialog", "Tout ignorer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
