# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\Operations_tree.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_operationOrganisator(object):
    def setupUi(self, Dialog_operationOrganisator):
        Dialog_operationOrganisator.setObjectName("Dialog_operationOrganisator")
        Dialog_operationOrganisator.resize(800, 700)
        Dialog_operationOrganisator.setMinimumSize(QtCore.QSize(500, 700))
        Dialog_operationOrganisator.setMaximumSize(QtCore.QSize(800, 700))
        self.labelTitle_operationsTree = QtWidgets.QLabel(Dialog_operationOrganisator)
        self.labelTitle_operationsTree.setGeometry(QtCore.QRect(0, 0, 801, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.labelTitle_operationsTree.setFont(font)
        self.labelTitle_operationsTree.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle_operationsTree.setObjectName("labelTitle_operationsTree")
        self.treeWidget = QtWidgets.QTreeWidget(Dialog_operationOrganisator)
        self.treeWidget.setGeometry(QtCore.QRect(10, 60, 780, 590))
        self.treeWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(2, "Export")
        self.pushButton_deleteOperation = QtWidgets.QPushButton(Dialog_operationOrganisator)
        self.pushButton_deleteOperation.setGeometry(QtCore.QRect(10, 660, 161, 28))
        self.pushButton_deleteOperation.setObjectName("pushButton_deleteOperation")
        self.pushButton_return = QtWidgets.QPushButton(Dialog_operationOrganisator)
        self.pushButton_return.setGeometry(QtCore.QRect(630, 660, 161, 28))
        self.pushButton_return.setObjectName("pushButton_return")
        self.pushButton_update_data = QtWidgets.QPushButton(Dialog_operationOrganisator)
        self.pushButton_update_data.setGeometry(QtCore.QRect(470, 660, 161, 28))
        self.pushButton_update_data.setObjectName("pushButton_update_data")

        self.retranslateUi(Dialog_operationOrganisator)
        QtCore.QMetaObject.connectSlotsByName(Dialog_operationOrganisator)
        Dialog_operationOrganisator.setTabOrder(self.treeWidget, self.pushButton_update_data)
        Dialog_operationOrganisator.setTabOrder(self.pushButton_update_data, self.pushButton_return)
        Dialog_operationOrganisator.setTabOrder(self.pushButton_return, self.pushButton_deleteOperation)

    def retranslateUi(self, Dialog_operationOrganisator):
        _translate = QtCore.QCoreApplication.translate
        Dialog_operationOrganisator.setWindowTitle(_translate("Dialog_operationOrganisator", "Dialog"))
        self.labelTitle_operationsTree.setText(_translate("Dialog_operationOrganisator", "<html><head/><body><p><span style=\" font-size:18pt; color:#3366cc;\">Organisateur d\'opérations</span></p></body></html>"))
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.headerItem().setText(0, _translate("Dialog_operationOrganisator", "1200"))
        self.treeWidget.headerItem().setText(1, _translate("Dialog_operationOrganisator", "Object"))
        self.treeWidget.headerItem().setText(3, _translate("Dialog_operationOrganisator", "Position"))
        self.treeWidget.headerItem().setText(4, _translate("Dialog_operationOrganisator", "ID"))
        self.pushButton_deleteOperation.setToolTip(_translate("Dialog_operationOrganisator", "<html><head/><body><p>L\'opération sera supprimée dans la structure de donnée mais restera présente dans l\'étude Salome.</p></body></html>"))
        self.pushButton_deleteOperation.setText(_translate("Dialog_operationOrganisator", "Supprimer l\'opération"))
        self.pushButton_return.setText(_translate("Dialog_operationOrganisator", "Retour au menu"))
        self.pushButton_update_data.setText(_translate("Dialog_operationOrganisator", "Mettre à jour la structure"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_operationOrganisator = QtWidgets.QDialog()
    ui = Ui_Dialog_operationOrganisator()
    ui.setupUi(Dialog_operationOrganisator)
    Dialog_operationOrganisator.show()
    sys.exit(app.exec_())
