# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\Reverse.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_reverse(object):
    def setupUi(self, Dialog_reverse):
        Dialog_reverse.setObjectName("Dialog_reverse")
        Dialog_reverse.resize(500, 340)
        Dialog_reverse.setMinimumSize(QtCore.QSize(500, 340))
        Dialog_reverse.setMaximumSize(QtCore.QSize(500, 340))
        self.labelTitle_Reverse = QtWidgets.QLabel(Dialog_reverse)
        self.labelTitle_Reverse.setGeometry(QtCore.QRect(0, 0, 500, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.labelTitle_Reverse.setFont(font)
        self.labelTitle_Reverse.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle_Reverse.setObjectName("labelTitle_Reverse")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog_reverse)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 461, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_select = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_select.setObjectName("label_select")
        self.verticalLayout.addWidget(self.label_select)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pb_add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_add.setObjectName("pb_add")
        self.horizontalLayout_3.addWidget(self.pb_add)
        self.pb_remove = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_remove.setObjectName("pb_remove")
        self.horizontalLayout_3.addWidget(self.pb_remove)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_entry = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_entry.setObjectName("label_entry")
        self.horizontalLayout_2.addWidget(self.label_entry)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textBrowser_selection_content = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser_selection_content.setObjectName("textBrowser_selection_content")
        self.verticalLayout.addWidget(self.textBrowser_selection_content)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog_reverse)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 300, 461, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_valider = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pb_valider.setObjectName("pb_valider")
        self.horizontalLayout.addWidget(self.pb_valider)
        self.pb_return = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pb_return.setObjectName("pb_return")
        self.horizontalLayout.addWidget(self.pb_return)

        self.retranslateUi(Dialog_reverse)
        QtCore.QMetaObject.connectSlotsByName(Dialog_reverse)
        Dialog_reverse.setTabOrder(self.pb_add, self.pb_remove)
        Dialog_reverse.setTabOrder(self.pb_remove, self.pb_valider)
        Dialog_reverse.setTabOrder(self.pb_valider, self.pb_return)

    def retranslateUi(self, Dialog_reverse):
        _translate = QtCore.QCoreApplication.translate
        Dialog_reverse.setWindowTitle(_translate("Dialog_reverse", "Dialog"))
        self.labelTitle_Reverse.setText(_translate("Dialog_reverse", "<html><head/><body><p><span style=\" font-size:18pt; color:#3366cc;\">Reverse wires</span></p></body></html>"))
        self.label_select.setText(_translate("Dialog_reverse", "Select wires to reverse:"))
        self.pb_add.setText(_translate("Dialog_reverse", "Add"))
        self.pb_remove.setText(_translate("Dialog_reverse", "Remove"))
        self.label_entry.setText(_translate("Dialog_reverse", "Entry:"))
        self.pb_valider.setText(_translate("Dialog_reverse", "Valider"))
        self.pb_return.setText(_translate("Dialog_reverse", "Retour"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_reverse = QtWidgets.QDialog()
    ui = Ui_Dialog_reverse()
    ui.setupUi(Dialog_reverse)
    Dialog_reverse.show()
    sys.exit(app.exec_())
